name: Publish EKS Accelerator

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, ubuntu]
    steps:          
      - uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: github-runner
          directory: images/github-runner
          registry: 164382793440.dkr.ecr.us-west-2.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}